// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dylazysgphnprtdhparl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5bGF6eXNncGhucHJ0ZGhwYXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTkxOTksImV4cCI6MjA3MDMzNTE5OX0.6rx5PrOEAkVP0RW-qd84LoqA8BEjZy8UlhCJEWVnSb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});